version: '3.5'

networks:
    uo-network:
        name: 'uo-network'
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"

services:
    servuo:
        hostname: servuo
        container_name: servuo
        build:
            context: .
            dockerfile: Dockerfile.dotnet
            target: servuo
        entrypoint: /usr/local/bin/docker-entrypoint.sh
        volumes:
            - ./ServUO/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
            - ${UO_DATA_PATH}:/UOData
            - ./ServUO/ServUO:/ServUO
        networks:
            uo-network:
        tty: true
    classicuo-build:
        container_name: classicuo-build
        build:
            context: .
            dockerfile: Dockerfile.dotnet
            target: classicuo
        entrypoint: /usr/local/bin/docker-entrypoint.sh
        volumes:
            - ./ClassicUO/docker-entrypoint.build.sh:/usr/local/bin/docker-entrypoint.sh
            - ${UO_DATA_PATH}:/UOData
            - ./ClassicUO/ClassicUO:/ClassicUO
    classicuo:
        depends_on:
            classicuo-build:
                condition: service_completed_successfully
        container_name: classicuo
        build:
            context: .
            dockerfile: Dockerfile.wine
        entrypoint: /usr/local/bin/docker-entrypoint.sh
        environment:
            DISPLAY: "${DISPLAY}"
            UO_SERVER_HOST: "${UO_SERVER_HOST}"
            UO_SERVER_PORT: "${UO_SERVER_PORT}"
            XDG_RUNTIME_DIR: "/var/run/user/1000"
        working_dir: /ClassicUO
        volumes:
            - ./ClassicUO/docker-entrypoint.run.sh:/usr/local/bin/docker-entrypoint.sh
            - ${UO_DATA_PATH}:/UOData
            - ./ClassicUO/ClassicUO:/ClassicUO
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ${XDG_RUNTIME_DIR}:/var/run/user/1000
            - ./Wine:/home/uouser/.wine
        networks:
            uo-network:
        # Run as privileged. Lazy way of getting all the devices available etc.
        privileged: true